-- Legacy tracking columns were removed from the orders table in the main schema.
-- This migration intentionally does nothing so older environments do not keep
-- re-running redundant cleanup steps.
